scrape_configs:
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']


  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'nginx-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginxexporter:9113']


  - job_name: 'redis-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['redisexporter:9121']

